// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxo5ngLj4a1FzcFlrRulaQ2QkqgVDIU8Y',
    appId: '1:61957962685:web:fdb2f311b52813344db0d4',
    messagingSenderId: '61957962685',
    projectId: 'tonalli-app',
    authDomain: 'tonalli-app.firebaseapp.com',
    storageBucket: 'tonalli-app.firebasestorage.app',
    measurementId: 'G-NFY54FFBXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMKshcXt6YMh1L5ak980tfxd3Nebn5Jf0',
    appId: '1:61957962685:android:5163ca2820c9760f4db0d4',
    messagingSenderId: '61957962685',
    projectId: 'tonalli-app',
    storageBucket: 'tonalli-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfP1pXGgco2fagZBMmFJh2bBrQnJ5eGoY',
    appId: '1:61957962685:ios:92f00f94d13e24f54db0d4',
    messagingSenderId: '61957962685',
    projectId: 'tonalli-app',
    storageBucket: 'tonalli-app.firebasestorage.app',
    iosBundleId: 'com.example.tonalliApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfP1pXGgco2fagZBMmFJh2bBrQnJ5eGoY',
    appId: '1:61957962685:ios:92f00f94d13e24f54db0d4',
    messagingSenderId: '61957962685',
    projectId: 'tonalli-app',
    storageBucket: 'tonalli-app.firebasestorage.app',
    iosBundleId: 'com.example.tonalliApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxo5ngLj4a1FzcFlrRulaQ2QkqgVDIU8Y',
    appId: '1:61957962685:web:87d071c29d05f2154db0d4',
    messagingSenderId: '61957962685',
    projectId: 'tonalli-app',
    authDomain: 'tonalli-app.firebaseapp.com',
    storageBucket: 'tonalli-app.firebasestorage.app',
    measurementId: 'G-5RECDSP79Z',
  );
}
